menu:
- {name: 'about', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'teaching', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Allie Balter-Kennedy', title: 'PhD Candidate', department: 'Lamont-Doherty Earth Observatory', institution: 'Columbia University', institution_address: 'New York, NY', phone: '(845) 365-8454', email: 'abalter@ldeo.columbia.edu', office: 'Comer 107', image: 'assets/img/headshot.jpg', url: 'primary-investigator'}


courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/alliebalter-kennedy'}
- {icon: 'twitter', link: 'https://twitter.com/alliebalter'}
#- {icon: 'instagram', link: 'https://instagram.com/paululele'}
#- {icon: 'linkedin', link: 'https://linkedin.com/in/lenpaul'}

contacts:
- {name: 'Allie Balter-Kennedy', title: 'PhD Candidate', department: 'Lamont-Doherty Earth Observatory', institution: 'Columbia University', institution_address: 'New York, NY', phone: '(845) 365-8454', email: 'abalter@ldeo.columbia.edu', office: 'Comer 107', image: 'assets/img/headshot.jpg'}
